### ISSUE TITLE
Not able to view the graph

### ISSUE THREAD

**Issue by andysingal** [dylanhogg/llmgraph#4]
```
## create graph
from pyvis.network import Network

net = Network(notebook=True, cdn_resources="in_line", directed=True)
net.show("/content/_output/machine-learning/artificial-intelligence/machine-learning_artificial-intelligence_v1.2.0_level3_incl_unprocessed.html")
```

<img width="1406" alt="Screenshot 2024-01-14 at 5 28 05 PM" src="https://github.com/dylanhogg/llmgraph/assets/20493493/df906aee-8c45-490c-b3a4-3945f71676df">

**Comment by dylanhogg** [comment]
It looks like you're running in Google Colab. The pyvis package uses quite a bit of javascript to view the graph which maybe why it's not displaying. I haven't tested in that environment, and looks like it doesn't work

Try downloading the html file from Colab to local and open in a browser, or run the llmgraph repo locally to create and view the html graph. NOte there are also other formats for you to load into graph apps like Gephi or alternatives.

**Comment by dylanhogg** [comment]
Looking at the pyvis docs, the show() method is for writing a static HTML file and saving locally, is that what you're trying to do here?
https://pyvis.readthedocs.io/en/latest/documentation.html#pyvis.network.Network.show

**Comment by andysingal** [comment]
Thanks for your instant reply, I have 2 questions
- How to display the graph using pyvis
- How to display entities on the graph, can i filter to show certain
entities.
Thanks & Regards,
Andy

**Comment by dylanhogg** [comment]
I don't know exactly off th top of my head, but I believe you need to load from the graphml file or gexf file (that is also outputted next to the html file) into a networkx object, then load that into pyvis before displaying

https://networkx.org/documentation/stable/reference/readwrite/graphml.html
https://pyvis.readthedocs.io/en/latest/documentation.html#pyvis.network.Network.from_nx

The html output is for convenient viewing i a browswer once the graph is complete, not a serialisation format for graphs

good luck

**Comment by andysingal** [comment]
I tried the following and it worked:
[image: Screenshot 2024-01-14 at 6.13.59 PM.png]
