### ISSUE TITLE
llama cpp/lm studio support?

### ISSUE THREAD

**Issue by KlausikPL** [dylanhogg/llmgraph#8]
hello this project has been updated 3 month ago I have question llmgraph support lm studio/llama cpp?

**Comment by dylanhogg** [comment]
You can specify a different LLM provider, including running with a local https://github.com/jmorganca/ollama model. 

You should be able to specify anything supported by [LiteLLM](https://github.com/BerriAI/litellm) as described here: https://docs.litellm.ai/docs/providers. 

Note that the prompts to extract related entities were tested with OpenAI and may not work as well with other models.

Thanks for your interest in the project.

**Comment by KlausikPL** [comment]
Thanks you
